### ISSUE TITLE
Go 1.10 now required due to undefined: strings.Builder

### ISSUE THREAD

**Issue by davefinster** [favadi/protoc-go-inject-tag#22]
This line was introduced in https://github.com/favadi/protoc-go-inject-tag/pull/20
https://github.com/favadi/protoc-go-inject-tag/blob/702215640cc61f347b0fd4fd4e46b318ab468370/file.go#L62

The Builder type was only added to ```strings``` in Go 1.10. Go get'ing this package currently results in
```bash
go get github.com/favadi/protoc-go-inject-tag
# github.com/favadi/protoc-go-inject-tag
go/src/github.com/favadi/protoc-go-inject-tag/file.go:62:14: undefined: strings.Builder
```
This should either be corrected to remove the dependence or the docs should be updated to indicate the minimum version requirement. I'm happy to have a crack at either, but comes down to what the project would prefer.

**Comment by favadi** [comment]
I'm fine with either. If you decided to support 1.9, please add a "1.9.x" line here: https://github.com/favadi/protoc-go-inject-tag/blob/master/.travis.yml#L11.
